/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ry2IjqkxxOV
 */


export function Newsletter() {
  return (
    (<div className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6 mx-auto max-w-7xl">
        <div className="flex flex-col items-center space-y-8 text-center">
          <div className="space-y-4">
            <h2
              className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
              Our Weekly Newsletter
            </h2>
            <p
              className="mx-auto max-w-prose text-gray-500 md:text-xl dark:text-gray-400">
              Stay updated with the latest news, articles, and resources, sent to your inbox weekly.
            </p>
          </div>
          <div className="prose prose-gray mx-auto max-w-prose dark:prose-invert">
            <p>
              Welcome to our weekly newsletter. We're excited to have you here and we promise to deliver the most
              relevant news and updates in our industry. Let's dive in!
            </p>
            <h3>Headline 1</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus
              ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.
            </p>
            <h3>Headline 2</h3>
            <p>
              Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec
              tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.
            </p>
            <h3>Headline 3</h3>
            <p>
              Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur
              sodales ligula in libero. Sed dignissim lacinia nunc.
            </p>
          </div>
        </div>
      </div>
    </div>)
  );
}
