/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ry2IjqkxxOV
 */

export function Newsletter() {
  return (
    <div className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6 mx-auto max-w-7xl">
        <div className="flex flex-col items-center space-y-8 text-center">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
              🚀 The AI Monitor - January 12, 2024
            </h2>
          </div>
          <div className="prose prose-gray mx-auto max-w-prose dark:prose-invert space-y-8 text-xl">
            <p>
              <strong>🤯 Supabase Hits 8k Members!</strong>
              <br />
              The AI community is thriving! 💻🌱 Supabase, the popular
              open-source alternative to Firebase, has now reached 8,000 members
              in its subreddit. This milestone puts Supabase in the same league
              as legendary subreddits like r/timelapsegrowery and r/Mesopotamia.
            </p>
            <p>
              <strong>📣 Weights & Biases Presents Carey Phelps</strong>
              <br />
              Join the NYC AI Community for an enlightening discussion with
              Carey Phelps, the founding PM of Weights & Biases. Dive into the
              AI milestones of 2023 and gain valuable insights on what's ahead
              in 2024. Register now to save your spot!
            </p>
            <p>
              <strong>📰 Semantic Router: A New Frontier in AI</strong>
              <br />
              James Briggs shares an insightful article on semantic router from
              Azhar41429690. Discover how this technology can revolutionize the
              GenAI landscape.
            </p>
            <p>
              <strong>📖 Abid Labs: A Pioneering AI Journey</strong>
              <br />
              Abubakar Abid, the founder of Abid Labs, shares an inspiring story
              of their AI journey. Congratulations to the team for their
              incredible achievements!
            </p>
            <p>
              <strong>🤝 Gradio: A Community Favorite</strong>
              <br />
              Everyone at LangLabs mentions Gradio at least 5 times a day! The
              tool has become an essential part of our AI automation work.
            </p>
            <p>
              <strong>👀 Stay Ahead with LangLabs</strong>
              <br />
              At LangLabs, we're dedicated to staying at the forefront of AI
              innovation. Trust us to deliver cutting-edge AI solutions for your
              business.
            </p>
            <p>
              Stay tuned for the next edition of The AI Monitor, where we'll
              bring you the latest news and insights from the ever-evolving
              world of AI.
            </p>
            <p>
              <em>The AI Monitor is a LangLabs production.</em>
            </p>
            <p>
              Follow us on Twitter:{" "}
              <a
                href="https://twitter.com/LangLabsIO"
                className="text-blue-500 hover:text-blue-600"
              >
                @LangLabsIO
              </a>
            </p>
            <p>
              Subscribe to our newsletter:{" "}
              <a
                href="https://letter.langlabs.io/"
                className="text-blue-500 hover:text-blue-600"
              >
                LangLabs Newsletter
              </a>
            </p>
            <p>
              Connect with us on LinkedIn:{" "}
              <a
                href="https://www.linkedin.com/company/langlabs/"
                className="text-blue-500 hover:text-blue-600"
              >
                LangLabs - AI Automation Agency
              </a>
            </p>
            <p>
              Visit our website:{" "}
              <a
                href="https://langlabs.io/"
                className="text-blue-500 hover:text-blue-600"
              >
                LangLabs
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
